version: '2.3'

services:
    ur_robot:
        build:
            context: .
            dockerfile: Dockerfile
        network_mode: "host"
        ipc: host
        environment:
            - ROS_DOMAIN_ID=2
            - DISPLAY
        volumes: 
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
        command: ros2 launch ur5_cell_moveit_config robot.launch.py