kinematics:
  shoulder:
    x: 0
    y: 0
    z: 0.16257940898924925
    roll: -0
    pitch: 0
    yaw: 4.1291485314287613e-08
  upper_arm:
    x: 4.9283955356545808e-05
    y: 0
    z: 0
    roll: 1.5698697657962171
    pitch: 0
    yaw: 5.036318121915316e-06
  forearm:
    x: -0.42545237634346178
    y: 0
    z: 0
    roll: 3.1392013464244997
    pitch: 3.1391688059969463
    yaw: -3.1415916373618824
  wrist_1:
    x: -0.39251793080369568
    y: 0.00011209320964041982
    z: 0.13371971283234207
    roll: 3.1407543838911054
    pitch: -3.1393367089449136
    yaw: 3.1415887695444389
  wrist_2:
    x: -5.0742574729960661e-05
    y: -0.099638455087368488
    z: 0.0001118519484761866
    roll: 1.5696737491576425
    pitch: 0
    yaw: 1.6248900383403209e-06
  wrist_3:
    x: 0.00015530393797499986
    y: 0.099482018028687641
    z: 0.00016221241847401644
    roll: 1.5724268955944378
    pitch: 3.1415926535897931
    yaw: 3.141592586202488
  hash: calib_11698609823524220358