joint_limits:
  shoulder_pan_joint:
    # acceleration limits are not publicly available
    has_acceleration_limits: true
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 150.0
    max_position: -0.35
    max_velocity: 1.57079632679
    min_position: -2.0
    max_acceleration: 3.49
  shoulder_lift_joint:
    # acceleration limits are not publicly available
    has_acceleration_limits: true
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 150.0
    max_position: 0.0
    max_velocity: 1.57079632679
    min_position: -3.14159265359
    max_acceleration: 3.49
  elbow_joint:
    # acceleration limits are not publicly available
    has_acceleration_limits: true
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 150.0
    max_position: 0.0
    max_velocity: 1.57079632679
    min_position: -3.14159265359
    max_acceleration: 3.49
  wrist_1_joint:
    # acceleration limits are not publicly available
    has_acceleration_limits: true
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 28.0
    max_position: 3.14159265359
    max_velocity: 1.57079632679
    min_position: -3.14159265359
    max_acceleration: 3.49
  wrist_2_joint:
    # acceleration limits are not publicly available
    has_acceleration_limits: true
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 28.0
    max_position: 3.14159265359
    max_velocity: 1.57079632679
    min_position: -3.14159265359
    max_acceleration: 3.49
  wrist_3_joint:
    # acceleration limits are not publicly available
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 28.0
    max_position: 3.14159265359
    max_velocity: 1.57079632679
    min_position: -3.14159265359
    has_acceleration_limits: true
    max_acceleration: 3.49
